# Client_Id
client_id=b41453f5-4099-4020-a1b3-8200b48abf95

# Client_Secret
client_secret=60c7ad2e-5722-49bb-a5da-08f43a2af68e

# GPTAPI KEY
gpt.API_KEY=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