# Client_Id
client_id=b41453f5-4099-4020-a1b3-8200b48abf95

# Client_Secret
client_secret=60c7ad2e-5722-49bb-a5da-08f43a2af68e

# GPTAPI KEY
gpt.API_KEY=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